[package]
name = "rc"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ureq = { version = "3.0.12", features = ["json"] }
